figma.showUI(__html__, { width: 360, height: 520 });

const COLORS = {
  bg: { r: 0.96, g: 0.97, b: 0.95 },
  white: { r: 1, g: 1, b: 1 },
  ink: { r: 0.03, g: 0.03, b: 0.035 },
  muted: { r: 0.47, g: 0.49, b: 0.48 },
  line: { r: 0.86, g: 0.88, b: 0.85 },
  lime: { r: 0.70, g: 1, b: 0.08 },
  panel: { r: 0.05, g: 0.055, b: 0.06 }
};

const DEVICES = [
  { id: 'small-android', label: 'Small Android', width: 360, height: 780 },
  { id: 'standard-android', label: 'Standard Android', width: 390, height: 844 },
  { id: 'large-phone', label: 'Large Phone', width: 430, height: 932 },
  { id: 'tablet-portrait', label: 'Tablet Portrait', width: 768, height: 1024 },
  { id: 'tablet-landscape', label: 'Tablet Landscape', width: 1024, height: 768 }
];

const DEFAULT_PACK = {
  name: 'ionPAY UIUX Agent Module Matrix',
  scope: 'design-only',
  owner: 'ionPAY UI/UX Execution Agent',
  devices: ['standard-android', 'tablet-portrait', 'tablet-landscape'],
  modules: [
    { title: 'Home', subtitle: 'Wallet PEN', amount: 'S/ 2,840.60', meta: 'Saldo disponible', actions: ['Pagar', 'Cobrar', 'Enviar', 'Historial'] },
    { title: 'Pagar', subtitle: 'Confirmacion previa', amount: 'S/ 18.50', meta: 'Sin falso exito', actions: ['QR', 'Codigo', 'PIN', 'Recibo'] },
    { title: 'Cobrar QR', subtitle: 'Solicitud editable', amount: 'S/ 60.00', meta: 'QR placeholder', actions: ['Compartir', 'Copiar', 'Cancelar', 'Recibo'] },
    { title: 'Comprobante', subtitle: 'Prueba de operacion', amount: 'S/ 18.50', meta: 'Trace ID visible', actions: ['Guardar', 'Compartir', 'Verificar', 'Cerrar'] },
    { title: 'Actividad', subtitle: 'Historial y pruebas', amount: '3 movimientos', meta: 'Estados visibles', actions: ['Todos', 'Cobros', 'Pagos', 'Pendientes'] },
    { title: 'Perfil', subtitle: 'Cuenta y seguridad', amount: 'KYC basico', meta: 'Limites visibles', actions: ['Seguridad', 'Limites', 'Dispositivos', 'Ayuda'] },
    { title: 'Merchant', subtitle: 'Cobro basico', amount: 'S/ 342.00', meta: 'Modo comercio', actions: ['Cobrar', 'QR', 'Link', 'Reporte'] },
    { title: '#ascii Receipt', subtitle: 'Terminal proof', amount: 'S/ 18.50', meta: 'STATE=COMPLETED', actions: ['SHARE', 'SAVE', 'VERIFY', 'CLOSE'], style: 'ascii' }
  ]
};

function fill(color) {
  return [{ type: 'SOLID', color }];
}

async function loadFonts() {
  await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
  await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
}

function createText(parent, name, value, x, y, width, size, color, align, bold) {
  const node = figma.createText();
  node.name = name;
  node.x = x;
  node.y = y;
  node.resize(width, 24);
  node.fontName = { family: 'Inter', style: bold ? 'Bold' : 'Regular' };
  node.characters = String(value || '');
  node.fontSize = size || 14;
  node.fills = fill(color || COLORS.ink);
  node.textAlignHorizontal = align || 'LEFT';
  node.lineHeight = { unit: 'AUTO' };
  parent.appendChild(node);
  return node;
}

function createFrame(parent, name, x, y, width, height, color, radius) {
  const node = figma.createFrame();
  node.name = name;
  node.x = x;
  node.y = y;
  node.resize(width, height);
  node.fills = fill(color || COLORS.white);
  node.cornerRadius = radius || 0;
  node.clipsContent = false;
  parent.appendChild(node);
  return node;
}

function addStroke(node, color) {
  node.strokes = fill(color || COLORS.line);
  node.strokeWeight = 1;
}

function createButton(parent, label, x, y, width, inverted) {
  const button = createFrame(parent, 'Button / ' + label, x, y, width, 44, inverted ? COLORS.lime : COLORS.ink, 14);
  createText(button, 'Label', label, 0, 14, width, 12, inverted ? COLORS.ink : COLORS.white, 'CENTER', true);
  return button;
}

function layoutForDevice(device) {
  const isTablet = device.width >= 700;
  const margin = isTablet ? 36 : 24;
  const contentWidth = device.width - margin * 2;
  return { isTablet, margin, contentWidth };
}

function createCoreScreen(parent, screen, device, index, originX, originY) {
  const layout = layoutForDevice(device);
  const frame = createFrame(parent, device.label + ' / ' + (screen.title || 'Untitled'), originX, originY, device.width, device.height, COLORS.white, device.width >= 700 ? 18 : 24);
  addStroke(frame, COLORS.ink);
  frame.clipsContent = true;

  const m = layout.margin;
  createText(frame, 'Device Label', device.label, m, 18, 220, 11, COLORS.muted, 'LEFT', true);
  createText(frame, 'Title', screen.title || 'Untitled', m, 52, layout.contentWidth, layout.isTablet ? 30 : 24, COLORS.ink, 'LEFT', true);
  createText(frame, 'Subtitle', screen.subtitle || 'Generated by ionPAY Screen Builder', m, layout.isTablet ? 90 : 84, layout.contentWidth, 12, COLORS.muted);

  const cardY = layout.isTablet ? 132 : 126;
  const cardH = layout.isTablet ? 180 : 160;
  const primaryWidth = layout.isTablet ? Math.min(360, layout.contentWidth * 0.44) : layout.contentWidth;
  const primary = createFrame(frame, 'Primary Card', m, cardY, primaryWidth, cardH, COLORS.ink, 24);
  createText(primary, 'Card Label', 'Main value', 24, 28, primaryWidth - 48, 12, COLORS.white);
  createText(primary, 'Amount', screen.amount || 'S/ 0.00', 24, 68, primaryWidth - 48, layout.isTablet ? 34 : 30, COLORS.white, 'LEFT', true);
  createText(primary, 'Meta', screen.meta || 'Wallet PEN', 24, cardH - 44, primaryWidth - 48, 12, COLORS.lime);

  const actions = Array.isArray(screen.actions) ? screen.actions : ['Pagar', 'Cobrar', 'Enviar', 'Historial'];
  const actionStartX = layout.isTablet ? m + primaryWidth + 28 : m;
  const actionStartY = layout.isTablet ? cardY : cardY + cardH + 34;
  const actionWidth = layout.isTablet ? Math.min(320, layout.contentWidth - primaryWidth - 28) : layout.contentWidth;
  actions.slice(0, 4).forEach((action, actionIndex) => {
    const cols = layout.isTablet ? 2 : 4;
    const gap = layout.isTablet ? 14 : 10;
    const itemW = Math.floor((actionWidth - gap * (cols - 1)) / cols);
    const itemX = actionStartX + (actionIndex % cols) * (itemW + gap);
    const itemY = actionStartY + Math.floor(actionIndex / cols) * 92;
    const item = createFrame(frame, 'Action / ' + action, itemX, itemY, itemW, 76, COLORS.white, 18);
    addStroke(item);
    const icon = createFrame(item, 'Icon', Math.max(12, itemW / 2 - 20), 9, 40, 40, COLORS.lime, 14);
    addStroke(icon, COLORS.ink);
    createText(icon, 'Icon Mark', String(action).slice(0, 2).toUpperCase(), 0, 12, 40, 11, COLORS.ink, 'CENTER', true);
    createText(item, 'Action Label', action, 0, 58, itemW, 10, COLORS.ink, 'CENTER', true);
  });

  const proofY = layout.isTablet ? 360 : 462;
  const proofWidth = layout.isTablet ? layout.contentWidth : layout.contentWidth;
  createText(frame, 'Section Title', 'Activity / Proof', m, proofY, 220, 16, COLORS.ink, 'LEFT', true);
  ['Trace ID ready', 'Receipt state visible', 'No false success'].forEach((line, rowIndex) => {
    const row = createFrame(frame, 'Proof Row / ' + line, m, proofY + 38 + rowIndex * 60, proofWidth, 50, COLORS.white, 14);
    addStroke(row);
    createText(row, 'Row Text', line, 18, 16, proofWidth - 36, 12, COLORS.ink);
  });

  createButton(frame, 'Continue', m, device.height - 98, layout.contentWidth, false);
  createText(frame, 'Trace', 'design-ops/ionpay-uiux-agent / design-only', m, device.height - 44, layout.contentWidth, 10, COLORS.muted);
}

function createAsciiScreen(parent, screen, device, index, originX, originY) {
  const layout = layoutForDevice(device);
  const frame = createFrame(parent, device.label + ' / ASCII / ' + (screen.title || 'Untitled'), originX, originY, device.width, device.height, COLORS.panel, 0);
  addStroke(frame, COLORS.lime);
  frame.clipsContent = true;
  const m = layout.margin;

  createText(frame, 'ASCII Device', '# ' + device.label, m, 20, layout.contentWidth, 11, COLORS.lime);
  createText(frame, 'ASCII Header Top', '+--------------------------------+', m, 56, layout.contentWidth, 12, COLORS.lime);
  createText(frame, 'ASCII Header Title', '| ' + (screen.title || 'IONPAY').padEnd(30, ' ') + ' |', m, 76, layout.contentWidth, 12, COLORS.lime);
  createText(frame, 'ASCII Header Bottom', '+--------------------------------+', m, 96, layout.contentWidth, 12, COLORS.lime);
  createText(frame, 'Amount', 'AMOUNT: ' + (screen.amount || 'S/ 0.00'), m, 154, layout.contentWidth, layout.isTablet ? 28 : 22, COLORS.white, 'LEFT', true);
  createText(frame, 'Meta', screen.meta || 'STATE=READY', m, 202, layout.contentWidth, 12, COLORS.lime);

  ['DEST=Wallet PEN', 'TRACE=ION-DESIGN', 'VERIFY=VISIBLE', 'FALSE_SUCCESS=BLOCKED'].forEach((line, rowIndex) => {
    createText(frame, 'ASCII Line ' + rowIndex, line, m + 10, 300 + rowIndex * 38, layout.contentWidth - 20, 12, COLORS.white);
  });

  createButton(frame, 'GENERATE PROOF', m, device.height - 98, layout.contentWidth, true);
  createText(frame, 'Trace', '#ascii design-only screen', m, device.height - 44, layout.contentWidth, 10, COLORS.lime);
}

function getDevices(pack) {
  const selected = Array.isArray(pack.devices) ? pack.devices : ['standard-android'];
  return DEVICES.filter((device) => selected.includes(device.id));
}

function createPack(pack) {
  const modules = Array.isArray(pack.modules) ? pack.modules : Array.isArray(pack.screens) ? pack.screens : [];
  const devices = getDevices(pack);
  const boardWidth = 40 + devices.reduce((sum, device) => sum + device.width + 60, 0);
  const rowHeight = Math.max(...devices.map((device) => device.height)) + 120;
  const boardHeight = 130 + modules.length * rowHeight;
  const pageFrame = createFrame(figma.currentPage, 'ionPAY Generated Matrix / ' + (pack.name || 'Untitled'), 0, 0, boardWidth, boardHeight, COLORS.bg, 24);
  addStroke(pageFrame, COLORS.ink);
  createText(pageFrame, 'Pack Title', pack.name || 'ionPAY Generated Matrix', 40, 36, boardWidth - 80, 28, COLORS.ink, 'LEFT', true);
  createText(pageFrame, 'Pack Note', 'Internal design tooling. Multi-device module matrix. Not app implementation.', 40, 74, boardWidth - 80, 14, COLORS.muted);

  modules.forEach((module, moduleIndex) => {
    const rowY = 130 + moduleIndex * rowHeight;
    createText(pageFrame, 'Module Label ' + moduleIndex, 'MODULE ' + String(moduleIndex + 1).padStart(2, '0') + ' / ' + module.title, 40, rowY - 28, boardWidth - 80, 16, COLORS.ink, 'LEFT', true);
    let x = 40;
    devices.forEach((device, deviceIndex) => {
      if (module.style === 'ascii') createAsciiScreen(pageFrame, module, device, deviceIndex, x, rowY);
      else createCoreScreen(pageFrame, module, device, deviceIndex, x, rowY);
      x += device.width + 60;
    });
  });
  figma.viewport.scrollAndZoomIntoView([pageFrame]);
}

async function runDefaultPack() {
  await loadFonts();
  createPack(DEFAULT_PACK);
  figma.notify('ionPAY UIUX module matrix generated.');
}

figma.ui.onmessage = async (message) => {
  if (message.type === 'generate') {
    await loadFonts();
    createPack(message.pack || DEFAULT_PACK);
    figma.notify('ionPAY screens generated.');
  }
};

runDefaultPack();
