figma.showUI(__html__, { width: 360, height: 520 });

const COLORS = {
  bg: { r: 0.96, g: 0.97, b: 0.95 },
  white: { r: 1, g: 1, b: 1 },
  ink: { r: 0.03, g: 0.03, b: 0.035 },
  muted: { r: 0.47, g: 0.49, b: 0.48 },
  line: { r: 0.86, g: 0.88, b: 0.85 },
  lime: { r: 0.70, g: 1, b: 0.08 },
  panel: { r: 0.05, g: 0.055, b: 0.06 }
};

const DEFAULT_PACK = {
  name: 'ionPAY UIUX Agent Starter Pack',
  scope: 'design-only',
  owner: 'ionPAY UI/UX Execution Agent',
  screens: [
    { title: 'Home', subtitle: 'Wallet PEN', amount: 'S/ 2,840.60', meta: 'Saldo disponible', actions: ['Pagar', 'Cobrar', 'Enviar', 'Historial'] },
    { title: 'Pagar', subtitle: 'Confirmacion previa', amount: 'S/ 18.50', meta: 'Sin falso exito', actions: ['QR', 'Codigo', 'PIN', 'Recibo'] },
    { title: 'Cobrar QR', subtitle: 'Solicitud editable', amount: 'S/ 60.00', meta: 'QR placeholder', actions: ['Compartir', 'Copiar', 'Cancelar', 'Recibo'] },
    { title: 'Comprobante', subtitle: 'Prueba de operacion', amount: 'S/ 18.50', meta: 'Trace ID visible', actions: ['Guardar', 'Compartir', 'Verificar', 'Cerrar'] },
    { title: 'Actividad', subtitle: 'Historial y pruebas', amount: '3 movimientos', meta: 'Estados visibles', actions: ['Todos', 'Cobros', 'Pagos', 'Pendientes'] },
    { title: '#ascii Receipt', subtitle: 'Terminal proof', amount: 'S/ 18.50', meta: 'STATE=COMPLETED', actions: ['SHARE', 'SAVE', 'VERIFY', 'CLOSE'], style: 'ascii' }
  ]
};

function fill(color) {
  return [{ type: 'SOLID', color }];
}

async function loadFonts() {
  await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
  await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
}

function createText(parent, name, value, x, y, width, size, color, align, bold) {
  const node = figma.createText();
  node.name = name;
  node.x = x;
  node.y = y;
  node.resize(width, 24);
  node.fontName = { family: 'Inter', style: bold ? 'Bold' : 'Regular' };
  node.characters = String(value || '');
  node.fontSize = size || 14;
  node.fills = fill(color || COLORS.ink);
  node.textAlignHorizontal = align || 'LEFT';
  node.lineHeight = { unit: 'AUTO' };
  parent.appendChild(node);
  return node;
}

function createFrame(parent, name, x, y, width, height, color, radius) {
  const node = figma.createFrame();
  node.name = name;
  node.x = x;
  node.y = y;
  node.resize(width, height);
  node.fills = fill(color || COLORS.white);
  node.cornerRadius = radius || 0;
  node.clipsContent = false;
  parent.appendChild(node);
  return node;
}

function addStroke(node, color) {
  node.strokes = fill(color || COLORS.line);
  node.strokeWeight = 1;
}

function createButton(parent, label, x, y, width, inverted) {
  const button = createFrame(parent, 'Button / ' + label, x, y, width, 44, inverted ? COLORS.lime : COLORS.ink, 14);
  createText(button, 'Label', label, 0, 14, width, 12, inverted ? COLORS.ink : COLORS.white, 'CENTER', true);
  return button;
}

function createCoreScreen(parent, screen, index) {
  const x = 40 + (index % 4) * 440;
  const y = 120 + Math.floor(index / 4) * 980;
  const frame = createFrame(parent, 'ionPAY Screen / ' + (screen.title || 'Untitled'), x, y, 402, 874, COLORS.white, 24);
  addStroke(frame, COLORS.ink);
  frame.clipsContent = true;

  createText(frame, 'Status Time', '9:41', 24, 20, 80, 12, COLORS.ink, 'LEFT', true);
  createText(frame, 'Title', screen.title || 'Untitled', 24, 58, 260, 24, COLORS.ink, 'LEFT', true);
  createText(frame, 'Subtitle', screen.subtitle || 'Generated by ionPAY Screen Builder', 24, 88, 320, 12, COLORS.muted);

  const primary = createFrame(frame, 'Primary Card', 24, 130, 354, 170, COLORS.ink, 24);
  createText(primary, 'Card Label', 'Main value', 24, 28, 160, 12, COLORS.white);
  createText(primary, 'Amount', screen.amount || 'S/ 0.00', 24, 68, 260, 34, COLORS.white, 'LEFT', true);
  createText(primary, 'Meta', screen.meta || 'Wallet PEN', 24, 126, 220, 12, COLORS.lime);

  const actions = Array.isArray(screen.actions) ? screen.actions : ['Pagar', 'Cobrar', 'Enviar', 'Historial'];
  actions.slice(0, 4).forEach((action, actionIndex) => {
    const item = createFrame(frame, 'Action / ' + action, 24 + actionIndex * 88, 340, 74, 82, COLORS.white, 18);
    addStroke(item);
    const icon = createFrame(item, 'Icon', 15, 10, 44, 44, COLORS.lime, 16);
    addStroke(icon, COLORS.ink);
    createText(icon, 'Icon Mark', String(action).slice(0, 2).toUpperCase(), 0, 13, 44, 11, COLORS.ink, 'CENTER', true);
    createText(item, 'Action Label', action, 0, 62, 74, 10, COLORS.ink, 'CENTER', true);
  });

  createText(frame, 'Section Title', 'Activity / Proof', 24, 470, 220, 16, COLORS.ink, 'LEFT', true);
  ['Trace ID ready', 'Receipt state visible', 'No false success'].forEach((line, rowIndex) => {
    const row = createFrame(frame, 'Proof Row / ' + line, 24, 510 + rowIndex * 68, 354, 56, COLORS.white, 14);
    addStroke(row);
    createText(row, 'Row Text', line, 18, 18, 260, 12, COLORS.ink);
  });

  createButton(frame, 'Continue', 24, 720, 354, false);
  createText(frame, 'Trace', 'design-ops/ionpay-uiux-agent', 24, 830, 300, 10, COLORS.muted);
}

function createAsciiScreen(parent, screen, index) {
  const x = 40 + (index % 4) * 440;
  const y = 120 + Math.floor(index / 4) * 980;
  const frame = createFrame(parent, 'ionPAY ASCII Screen / ' + (screen.title || 'Untitled'), x, y, 402, 874, COLORS.panel, 0);
  addStroke(frame, COLORS.lime);
  frame.clipsContent = true;

  createText(frame, 'ASCII Header Top', '+--------------------------------+', 24, 40, 340, 12, COLORS.lime);
  createText(frame, 'ASCII Header Title', '| ' + (screen.title || 'IONPAY').padEnd(30, ' ') + ' |', 24, 60, 340, 12, COLORS.lime);
  createText(frame, 'ASCII Header Bottom', '+--------------------------------+', 24, 80, 340, 12, COLORS.lime);
  createText(frame, 'Amount', 'AMOUNT: ' + (screen.amount || 'S/ 0.00'), 24, 150, 320, 24, COLORS.white, 'LEFT', true);
  createText(frame, 'Meta', screen.meta || 'STATE=READY', 24, 198, 320, 12, COLORS.lime);

  ['DEST=Wallet PEN', 'TRACE=ION-DESIGN', 'VERIFY=VISIBLE', 'FALSE_SUCCESS=BLOCKED'].forEach((line, rowIndex) => {
    createText(frame, 'ASCII Line ' + rowIndex, line, 34, 300 + rowIndex * 38, 320, 12, COLORS.white);
  });

  createButton(frame, 'GENERATE PROOF', 24, 700, 354, true);
  createText(frame, 'Trace', '#ascii design-only screen', 24, 830, 300, 10, COLORS.lime);
}

function createPack(pack) {
  const screens = Array.isArray(pack.screens) ? pack.screens : [];
  const boardHeight = screens.length > 4 ? 2100 : 1100;
  const pageFrame = createFrame(figma.currentPage, 'ionPAY Generated Pack / ' + (pack.name || 'Untitled'), 0, 0, 1860, boardHeight, COLORS.bg, 24);
  addStroke(pageFrame, COLORS.ink);
  createText(pageFrame, 'Pack Title', pack.name || 'ionPAY Generated Pack', 40, 36, 900, 28, COLORS.ink, 'LEFT', true);
  createText(pageFrame, 'Pack Note', 'Internal design tooling. Not app implementation. Observer agents may inspect only.', 40, 74, 1200, 14, COLORS.muted);
  screens.forEach((screen, index) => {
    if (screen.style === 'ascii') createAsciiScreen(pageFrame, screen, index);
    else createCoreScreen(pageFrame, screen, index);
  });
  figma.viewport.scrollAndZoomIntoView([pageFrame]);
}

async function runDefaultPack() {
  await loadFonts();
  createPack(DEFAULT_PACK);
  figma.notify('ionPAY UIUX starter pack generated.');
}

figma.ui.onmessage = async (message) => {
  if (message.type === 'generate') {
    await loadFonts();
    createPack(message.pack || DEFAULT_PACK);
    figma.notify('ionPAY screens generated.');
  }
};

runDefaultPack();
