figma.showUI(__html__, { width: 360, height: 520 });

const COLORS = {
  bg: { r: 0.96, g: 0.97, b: 0.95 },
  white: { r: 1, g: 1, b: 1 },
  ink: { r: 0.03, g: 0.03, b: 0.035 },
  muted: { r: 0.47, g: 0.49, b: 0.48 },
  line: { r: 0.86, g: 0.88, b: 0.85 },
  lime: { r: 0.70, g: 1, b: 0.08 }
};

function fill(color) {
  return [{ type: 'SOLID', color }];
}

async function loadFonts() {
  await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
  await figma.loadFontAsync({ family: 'Inter', style: 'Bold' });
}

function createText(parent, name, value, x, y, width, size, color, align) {
  const node = figma.createText();
  node.name = name;
  node.x = x;
  node.y = y;
  node.resize(width, 24);
  node.fontName = { family: 'Inter', style: 'Regular' };
  node.characters = String(value || '');
  node.fontSize = size || 14;
  node.fills = fill(color || COLORS.ink);
  node.textAlignHorizontal = align || 'LEFT';
  parent.appendChild(node);
  return node;
}

function createFrame(parent, name, x, y, width, height, color, radius) {
  const node = figma.createFrame();
  node.name = name;
  node.x = x;
  node.y = y;
  node.resize(width, height);
  node.fills = fill(color || COLORS.white);
  node.cornerRadius = radius || 0;
  node.clipsContent = false;
  parent.appendChild(node);
  return node;
}

function addStroke(node) {
  node.strokes = fill(COLORS.line);
  node.strokeWeight = 1;
}

function createButton(parent, label, x, y, width) {
  const button = createFrame(parent, 'Button / ' + label, x, y, width, 44, COLORS.ink, 14);
  createText(button, 'Label', label, 0, 14, width, 12, COLORS.white, 'CENTER');
  return button;
}

function createScreen(parent, screen, index) {
  const x = 40 + index * 440;
  const frame = createFrame(parent, 'ionPAY Screen / ' + (screen.title || 'Untitled'), x, 120, 402, 874, COLORS.white, 24);
  addStroke(frame);
  frame.clipsContent = true;

  createText(frame, 'Status Time', '9:41', 24, 20, 80, 12, COLORS.ink);
  createText(frame, 'Title', screen.title || 'Untitled', 24, 58, 260, 24, COLORS.ink);
  createText(frame, 'Subtitle', screen.subtitle || 'Generated by ionPAY Screen Builder', 24, 88, 320, 12, COLORS.muted);

  const balance = createFrame(frame, 'Primary Card', 24, 130, 354, 170, COLORS.ink, 24);
  createText(balance, 'Card Label', 'Main value', 24, 28, 160, 12, COLORS.white);
  createText(balance, 'Amount', screen.amount || 'S/ 0.00', 24, 68, 260, 34, COLORS.white);
  createText(balance, 'Meta', screen.meta || 'Wallet PEN', 24, 126, 200, 12, COLORS.lime);

  const actions = Array.isArray(screen.actions) ? screen.actions : ['Pagar', 'Cobrar', 'Enviar', 'Historial'];
  actions.slice(0, 4).forEach((action, actionIndex) => {
    const item = createFrame(frame, 'Action / ' + action, 24 + actionIndex * 88, 340, 74, 82, COLORS.white, 18);
    addStroke(item);
    const icon = createFrame(item, 'Icon', 15, 10, 44, 44, COLORS.lime, 16);
    createText(icon, 'Icon Mark', String(action).slice(0, 2).toUpperCase(), 0, 13, 44, 11, COLORS.ink, 'CENTER');
    createText(item, 'Action Label', action, 0, 62, 74, 10, COLORS.ink, 'CENTER');
  });

  createText(frame, 'Section Title', 'Activity / Proof', 24, 470, 220, 16, COLORS.ink);
  ['Trace ID ready', 'Receipt state visible', 'No false success'].forEach((line, rowIndex) => {
    const row = createFrame(frame, 'Proof Row / ' + line, 24, 510 + rowIndex * 68, 354, 56, COLORS.white, 14);
    addStroke(row);
    createText(row, 'Row Text', line, 18, 18, 260, 12, COLORS.ink);
  });

  createButton(frame, 'Continue', 24, 720, 354);
  createText(frame, 'Trace', 'Generated by design-ops/ionpay-uiux-agent', 24, 830, 300, 10, COLORS.muted);
}

figma.ui.onmessage = async (message) => {
  if (message.type === 'generate') {
    await loadFonts();
    const pack = message.pack || {};
    const pageFrame = createFrame(figma.currentPage, 'ionPAY Generated Pack / ' + (pack.name || 'Untitled'), 0, 0, 2200, 1100, COLORS.bg, 24);
    createText(pageFrame, 'Pack Title', pack.name || 'ionPAY Generated Pack', 40, 36, 900, 28, COLORS.ink);
    createText(pageFrame, 'Pack Note', 'Internal design tooling. Not app implementation.', 40, 74, 900, 14, COLORS.muted);
    const screens = Array.isArray(pack.screens) ? pack.screens : [];
    screens.forEach((screen, index) => createScreen(pageFrame, screen, index));
    figma.viewport.scrollAndZoomIntoView([pageFrame]);
    figma.notify('ionPAY screens generated.');
  }

  if (message.type === 'error') {
    figma.notify(message.message || 'Plugin error.');
  }
};
